/**
 * Auto-generated TypeScript types from OpenAPI spec.
 *
 * Run `npm run gen:api` (with the backend running) to regenerate.
 * This is a placeholder — the real file is generated by openapi-typescript.
 */

export interface paths {
  "/api/v2/auth/check": {
    get: {
      responses: {
        /** @description Success */
        200: {
          content: {
            "application/json": {
              ok: boolean;
              data: { required: boolean };
              error: null;
            };
          };
        };
      };
    };
  };
  "/api/v2/auth/login": {
    post: {
      requestBody: {
        content: {
          "application/json": {
            password: string;
          };
        };
      };
      responses: {
        /** @description Success */
        200: {
          content: {
            "application/json": {
              ok: boolean;
              data: { token: string };
              error: null | string;
            };
          };
        };
      };
    };
  };
  "/api/v2/platforms": {
    get: {
      responses: {
        200: {
          content: {
            "application/json": {
              ok: boolean;
              data: unknown[];
              error: null;
            };
          };
        };
      };
    };
  };
  "/api/v2/stats/overview": {
    get: {
      responses: {
        200: {
          content: {
            "application/json": {
              ok: boolean;
              data: {
                total_registrations: number;
                success: number;
                failed: number;
                success_rate: number;
                total_accounts: number;
                account_distribution: Record<string, number>;
              };
              error: null;
            };
          };
        };
      };
    };
  };
}

export interface components {
  schemas: {
    ApiResponse: {
      ok: boolean;
      data: unknown;
      error: string | null;
    };
  };
}
